# -*- mode: zsh -*-
# vim: set ft=sh :

export TERM="xterm-256color"
ZSH_THEME="powerlevel9k/powerlevel9k"

prompt_context() {}

plugins=(
  git
  zsh-autosuggestions
  history-substring-search
)

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time)
POWERLEVEL9K_PROMPT_ON_NEWLINE=false
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='red'
# Add a space in the first prompt
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%f"
# Visual customisation of the second prompt line
local user_symbol="$"
if [[ $(print -P "%#") =~ "#" ]]; then
    user_symbol = "#"
fi
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%{%B%F{black}%K{yellow}%} $user_symbol%{%b%f%k%F{yellow}%} %{%f%}"


source /Users/$(whoami)/dotfiles/zsh/zsh_profile
# source ~/dotfiles/zsh/zsh_profile
source ~/dotfiles/zsh/zsh_aliases

