# -*- mode: zsh -*-
# vim: set ft=sh :

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export TERM="xterm-256color"
ZSH_THEME="powerlevel10k/powerlevel10k" 

prompt_context() {}

plugins=(
  git
  zsh-autosuggestions
  history-substring-search
)

# Visual customisation of the second prompt line
local user_symbol="$"
if [[ $(print -P "%#") =~ "#" ]]; then
    user_symbol = "#"
fi

source $ZSH/oh-my-zsh.sh

source "$HOME/.sdkman/bin/sdkman-init.sh"
source ~/.zsh_profile
source ~/dotfiles/zsh/zsh_profile
source $HOME/dotfiles/zsh/zsh_aliases

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

