---
- name: setup home directory
  hosts: localhost
  connection: local
  # gather_facts: false

  tasks:

    # https://stackoverflow.com/questions/32374349/how-to-create-dynamic-variables-in-ansible
    - set_fact:
        user_home_dir: "{{lookup('env', 'HOME') }}"

    - name: Install npm packages
      community.general.npm:
        name: "{{ item }}"
        global: yes
        state: present
      loop:
        - typescript
        - live-server
        - prettier
        - typescript-language-server
        - lua-fmt
        - markdownlint
        - markdownlint-cli
        - yaml-language-server
        - dockerfile-language-server-nodejs
        - bash-language-server
        - vim-language-server
        - sql-language-server


# symlinks
# ${HOME}/bin/launch_jdtls.sh -> ${HOME}/dotfiles/nvim/jdtls/launch-jdtls.sh

  # 4. symlink from Users/rnkoaa/dotfiles/nvim/jdtls/launch-jdtls.sh to ~/bin/launch-jdtls (executable)
  #
  # Creates a symlink

  # https://github.com/google/google-java-format/releases/download/v1.14.0/google-java-format-1.14.0-all-deps.jar
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
  # - name: download google-java-format
  #   ansible.builtin.get_url:
  #     src: {{ google_java_formatter_url }}
  #     dest: ~/.config/formatters/google-java-format-{{ google_java_version }}-all-deps.jar

#  git clone git@github.com:eclipse/eclipse.jdt.ls.git >> ~/.config/eclipse.jdt.ls
#  https://github.com/fwcd/kotlin-language-server
#  https://github.com/GroovyLanguageServer/groovy-language-server
