---
- name: setup home directory
  hosts: localhost
  connection: local
  # gather_facts: false

  tasks:

    # https://stackoverflow.com/questions/32374349/how-to-create-dynamic-variables-in-ansible
    - set_fact:
        user_home_dir: "{{lookup('env', 'HOME') }}"

    - name: "Install apps via brew on command line"
      ansible.builtin.shell: "arch -{{ ansible_architecture }} brew install {{ item }}"
      loop: 
      - exa
      - bat
      - broot
      - wget
      - curl
      - fd
      - jq
      - fzf
      - httpie
      - ripgrep
      - tree
      - neovim
      - tmux
      - sqlite3
      - zoxide
      - lua
      - jq
      - tree-sitter
      - lua-language-server

    - name: Install npm packages
      community.general.npm:
        name: "{{ item }}"
        global: yes
        state: present
      loop:
        - typescript
        - liveserver
        - prettier
        - typescript-language-server
        - lua-fmt
        - yaml-language-server
        - dockerfile-language-server-nodejs
        - bash-language-server
        - vim-language-server
        

    - name: Ensure expected directories exists
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - ~/.config/
        # - ~/.config/nvim
        - ~/.config/formatters

    - name: Create a symbolic link
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop:
        - {src: "{{user_home_dir}}/dotfiles/zsh/.zshrc", dest: "{{user_home_dir}}/.zshrc"}
        - {src: "{{user_home_dir}}/dotfiles/zsh/.zsh_profile", dest: "{{user_home_dir}}/.zsh_profile"}
        - {src: "{{user_home_dir}}/dotfiles/zsh/.zsh_aliases", dest: "{{user_home_dir}}/.zsh_aliases"}
        
        # tmux configs
        - {src: "{{user_home_dir}}/dotfiles/tmux/.tmux.conf", dest: "{{user_home_dir}}/.tmux.conf"}
        - {src: "{{user_home_dir}}/dotfiles/tmux/.tmux.conf.local", dest: "{{user_home_dir}}/.tmux.conf.local"}

        # .ideavimrc configs
        - {src: "{{user_home_dir}}/dotfiles/ideavim/.ideavimrc", dest: "{{user_home_dir}}/.ideavimrc"}
        
        # .ideavimrc configs
        - {src: "{{user_home_dir}}/dotfiles/nvim", dest: "{{user_home_dir}}/.config/nvim"}



# symlinks
# ${HOME}/.config/nvim -> ${HOME}/dotfiles/nvim
# ${HOME}/.config/alacritty -> ${HOME}/dotfiles/alacritty
# ${HOME}/bin/launch_jdtls.sh -> ${HOME}/dotfiles/nvim/jdtls/launch-jdtls.sh

  # 1. Creates a nvim directory from dotfiles to ~/.config/nvim
  # 2. Creates a alacritty directory from dotfiles to ~/.config/alacritty
  # 3. Creates a iterm2 directory from dotfiles to ~/.config/alacritty
  # 4. symlink from Users/rnkoaa/dotfiles/nvim/jdtls/launch-jdtls.sh to ~/bin/launch-jdtls (executable)
  # 5. symlink .zshrc, .zsh_profile, .zsh_history
  #
  # Creates a symlink

  # https://github.com/google/google-java-format/releases/download/v1.14.0/google-java-format-1.14.0-all-deps.jar
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
  # - name: download google-java-format
  #   ansible.builtin.get_url:
  #     src: {{ google_java_formatter_url }}
  #     dest: ~/.config/formatters/google-java-format-{{ google_java_version }}-all-deps.jar



#
#  jq
#
#  git clone  git@github.com:eclipse/eclipse.jdt.ls.git >> ~/.config/eclipse.jdt.ls
#  https://github.com/fwcd/kotlin-language-server
#  https://github.com/GroovyLanguageServer/groovy-language-server
